name: malibo
channels:
- defaults
- conda-forge
dependencies:
- python=3.11
- pip
- pip:
    - blackboxopt==5.0.4
    - matplotlib==3.9.1
    - numpy==2.0.1
    - pandas==2.2.2
    - parameterspace==0.10.0
    - scikit-learn==1.5.1
    - scipy==1.14.0
    - torch==2.4.0
    - tqdm==4.66.4
